#!/usr/bin/env node
'use strict';
// Compiles tools/icons/src/<set>/*.svg into public/js/icons.js: the icon registry
// and its sprite builder (plan D4.2). Every <path> of every source is kept, in order
// (the v1.x podcast icon kept one path of three; icons-registry.test.js re-derives
// each entry from its source and compares).
//
//   node tools/icons/build.js [--check]     (--check: exit 1 if icons.js is stale)

const fs = require('node:fs');
const path = require('node:path');
const { NAMES, FILL, STYLES } = require('./names');

const SRC = path.join(__dirname, 'src');
const OUT = path.join(__dirname, '..', '..', 'public', 'js', 'icons.js');
const VB = '0 -960 960 960';

// One source file -> { vb, d } (d = the paths joined; a multi-path icon keeps them all).
function parseSource(file) {
  const svg = fs.readFileSync(file, 'utf8');
  // A source without a viewBox (push_pin) draws in its width x height box.
  const w = /\bwidth="(\d+)"/.exec(svg);
  const h = /\bheight="(\d+)"/.exec(svg);
  const vb = /viewBox="([^"]+)"/.exec(svg) || (w && h ? [null, `0 0 ${w[1]} ${h[1]}`] : null);
  const ds = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)].map((m) => m[1]);
  if (!vb || !ds.length) throw new Error(`unreadable icon source: ${file}`);
  if (/<(circle|rect|polygon|ellipse|line|polyline|g)\b/.test(svg)) throw new Error(`non-path shape in ${file}: extend build.js`);
  return { vb: vb[1], d: ds.join('') };
}

function registry() {
  const out = {};
  for (const set of Object.keys(STYLES)) {
    out[set] = {};
    for (const name of NAMES) {
      const files = [[name, name]];
      if (FILL.includes(name)) files.push([`${name}.fill`, `${name}.fill`]);
      for (const [key, file] of files) {
        const { vb, d } = parseSource(path.join(SRC, set, `${file}.svg`));
        out[set][key] = vb === VB ? d : [vb, d];
      }
    }
  }
  return out;
}

function render(reg) {
  const sets = Object.keys(reg).map((set) => {
    const entries = Object.entries(reg[set]).map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
    return `  ${set}: {\n${entries}\n  },`;
  }).join('\n');
  return `// GENERATED by tools/icons/build.js from tools/icons/src - do not edit by hand.
// Material Symbols (Apache-2.0, (c) Google): https://github.com/google/material-design-icons
//
// The icon registry (UI professionalism pass, plan D4.2): { set: { name: path data } }
// for the three icon sets of the data-icons axis. A value is the path data in the
// Material '${VB}' box, or [viewBox, d] for any other box. 'name.fill' is the
// FILL=1 variant (on-states). Markup references an icon as
//   <svg class="ui-icon"><use href="#i-NAME"/></svg>   ('keep.fill' -> #i-keep-fill)
// and inject() puts the current set's <symbol>s in a hidden sprite at the top of
// <body> (each shell calls it from the first script in <body>, so nothing pops in);
// calling it again with another set swaps the sprite in place.
(function (root) {
  'use strict';
  const VB = '${VB}';
  const ICONS = {
${sets}
  };
  const SPRITE_ID = 'ft-icon-sprite';
  const symbolId = (name) => 'i-' + name.replace(/\\./g, '-');
  const resolveSet = (set) => (Object.prototype.hasOwnProperty.call(ICONS, set) ? set : 'outlined');

  function spriteSymbols(set) {
    const icons = ICONS[resolveSet(set)];
    return Object.keys(icons).map((name) => {
      const v = icons[name];
      const vb = typeof v === 'string' ? VB : v[0];
      const d = typeof v === 'string' ? v : v[1];
      return '<symbol id="' + symbolId(name) + '" viewBox="' + vb + '"><path d="' + d + '"/></symbol>';
    }).join('');
  }

  // Injects (or swaps) the sprite for \`set\` (default: <html data-icons>). Safe to call
  // before the rest of <body> has parsed; a no-op without a DOM.
  function inject(set, doc) {
    const d = doc || (typeof document !== 'undefined' ? document : null);
    if (!d || !d.body) return null;
    const chosen = resolveSet(set || d.documentElement.getAttribute('data-icons'));
    let sprite = d.getElementById(SPRITE_ID);
    if (!sprite) {
      sprite = d.createElementNS('http://www.w3.org/2000/svg', 'svg');
      sprite.setAttribute('id', SPRITE_ID);
      sprite.setAttribute('aria-hidden', 'true');
      sprite.setAttribute('focusable', 'false');
      sprite.setAttribute('hidden', '');
      // Belt for the stylesheet's #ft-icon-sprite { display: none }: the HTML [hidden] rule
      // does not reach an SVG-namespace element, and a sized <svg> would take 300x150.
      sprite.setAttribute('width', '0');
      sprite.setAttribute('height', '0');
      d.body.insertBefore(sprite, d.body.firstChild);
    }
    if (sprite.getAttribute('data-set') !== chosen) {
      sprite.innerHTML = spriteSymbols(chosen);
      sprite.setAttribute('data-set', chosen);
    }
    return sprite;
  }

  const has = (name) => Object.prototype.hasOwnProperty.call(ICONS.outlined, name);
  const api = { ICONS, VB, SPRITE_ID, symbolId, spriteSymbols, inject, has, names: () => Object.keys(ICONS.outlined) };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.FTIcons = api;
})(typeof self !== 'undefined' ? self : this);
`;
}

module.exports = { registry, render, parseSource, OUT };

if (require.main === module) {
  const text = render(registry());
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (cur !== text) { console.error('icons: public/js/icons.js is stale - run node tools/icons/build.js'); process.exit(1); }
    console.log('icons: public/js/icons.js is current');
  } else {
    fs.writeFileSync(OUT, text);
    console.log(`icons: wrote ${path.relative(process.cwd(), OUT)} (${text.length} bytes, ${NAMES.length} names + ${FILL.length} fills x ${Object.keys(STYLES).length} sets)`);
  }
}
